pipeline:
    compile:
        image: microsoft/aspnetcore-build
        commands:
        - sh build.sh
    build-image:
        commands:
        - docker build -t hardik2205/dotnetcore-container ./Web
