kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username: hardik2205
    password: 
      from_secret: my-dockerhub-password
    repo: hardik2205/dotnetcore-container
    dockerfile: Web/Dockerfile
